name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install python-dev
      run: sudo apt-get -y install python-dev
    - name: Install diesel_cli mysql
      run: cargo install diesel_cli --no-default-features --features mysql
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
