name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install mysqlclient prerequisites
      run: sudo apt-get install python-dev default-libmysqlclient-de
    - name: Install mysqlclient
      run: pip install mysqlclient
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
